name: Secrets and Environment variables

on: workflow_dispatch
env:
  SUPER_SECRET: ${{ secrets.TG_TOKEN }}
jobs:
  top-secret:
    runs-on: ununtu-latest
    env:
      super_secret: ${{ secrets.TG_TOKEN }}
    steps:
      - name: Hello world action
        run: echo "${{secrets.TG_TOKEN}}"

    
