name: Secrets and Environment variables

on: 
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ununtu-latest
    env:
      super_secret: ${{ secrets.TG_TOKEN }}

    steps:
      - name: Hello world action
        run: echo "${{secrets.TG_TOKEN}}"

      - name: Run Tests (JEST)
        run: yarn test --ci --silent --testPathIgnorePatterns=experimental
        env:
          CI: true
          API_KEY: ${{ secrets.TG_TOKEN }}

    
